const Detailsstyles = {
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
  },
  TextBox: {
    backgroundColor: '#fff',
    width: '100%',
    height: '70%',
    borderBottomEndRadius: 15,
    borderBottomLeftRadius: 15,
    borderTopWidth: 0.5,
  },
  ImageBox: {
    width: '100%',
    height: '30%',
  },
  tandC: {
    margin: 15,
  },
  title: {
    margin: 5,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
  },
  Cata: {
    fontSize: 15,
    margin: 5,
  },
  price: {
    fontSize: 20,
    fontWeight: 'bold',
    fontStyle: 'normal',
    color: '#e63946',
    marginHorizontal: 15,
  },
  buyButton: {
    borderWidth: 1,
    borderRadius: 30,
    width: '30%',
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#264653',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.55,
    shadowRadius: 14.78,
    elevation: 12,
  },
  DT: {
    fontSize: 18,
    fontWeight: 'bold',
    marginVertical: 10,
    color: '#000',
  },
  Description: {
    backgroundColor: '#fff',
    width: '95%',
    height: 220,
    padding: 10,
    margin: 10,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.55,
    shadowRadius: 14.78,
    elevation: 22,
  },
  des: {
    fontSize: 15,
    color: '#000',
  },
  buyButton: {
    borderRadius: 30,
    width: '80%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e63946',
    margin: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.55,
    shadowRadius: 14.78,
    elevation: 22,
  },
};
export default Detailsstyles;
